#!/bin/bash
# session-env-loader.sh — Bridge: SOPS-encrypted secrets → Claude Code Session
# Laedt alle ~/.config/secrets/env.d/*.env (SOPS-verschluesselt) in CLAUDE_ENV_FILE
# Fallback (Bug #15840): Schreibt sourceable Cache-Datei + additionalContext
# Siehe: ADR-003 (projekt-automation-hub/docs/decisions/ADR-003-config-architecture.md)

ENV_DIR="${XDG_CONFIG_HOME:-$HOME/.config}/secrets/env.d"
CACHE_FILE="${XDG_CONFIG_HOME:-$HOME/.config}/secrets/.env-cache"
IS_MINGW=false
if [[ "$(uname -s)" == MINGW* ]] || [[ "$(uname -s)" == MSYS* ]]; then
  IS_MINGW=true
fi

# SOPS braucht Windows-Pfade auf MINGW/MSYS (nicht /c/Users/... sondern C:\Users\...)
if $IS_MINGW; then
  export SOPS_AGE_KEY_FILE="$(cygpath -w "$HOME/.config/secrets/age-key.txt")"
else
  export SOPS_AGE_KEY_FILE="$HOME/.config/secrets/age-key.txt"
fi

# Helper: Pfad fuer sops konvertieren (MINGW → Windows)
sops_path() {
  if $IS_MINGW; then cygpath -w "$1"; else echo "$1"; fi
}

# --- Decrypt all env files into memory ---
ALL_LINES=""
LOADED=0

if [ -d "$ENV_DIR" ]; then
  for env_file in "$ENV_DIR"/*.env; do
    [ -f "$env_file" ] || continue
    decrypted=$(sops -d "$(sops_path "$env_file")" 2>/dev/null)
    if [ $? -ne 0 ]; then
      decrypted=$(cat "$env_file")
    fi
    while IFS= read -r line || [ -n "$line" ]; do
      line="${line%$'\r'}"
      [[ "$line" =~ ^[[:space:]]*# ]] && continue
      [[ -z "${line// }" ]] && continue
      # Platform-Translation: WSL2-Pfade (/mnt/c/) auf MINGW-Format (/c/)
      if $IS_MINGW; then
        line=$(echo "$line" | sed 's|/mnt/c/|/c/|g')
      fi
      ALL_LINES="${ALL_LINES}${line}"$'\n'
      ((LOADED++))
    done <<< "$decrypted"
  done
fi

# --- Always write sourceable cache file (chmod 600) ---
if [ "$LOADED" -gt 0 ]; then
  printf '#!/bin/bash\n# Auto-generated by session-env-loader.sh — DO NOT EDIT\n# Source this file: source "%s"\n' "$CACHE_FILE" > "$CACHE_FILE"
  while IFS= read -r line || [ -n "$line" ]; do
    [ -z "$line" ] && continue
    echo "export $line" >> "$CACHE_FILE"
  done <<< "$ALL_LINES"
  chmod 600 "$CACHE_FILE"
fi

# --- Path 1: CLAUDE_ENV_FILE available (ideal) ---
if [ -n "$CLAUDE_ENV_FILE" ]; then
  while IFS= read -r line || [ -n "$line" ]; do
    [ -z "$line" ] && continue
    echo "export $line" >> "$CLAUDE_ENV_FILE"
  done <<< "$ALL_LINES"
  echo '{"systemMessage":"env-loader: '"$LOADED"' vars loaded into CLAUDE_ENV_FILE + cache, platform='"$(uname -s)"'"}'
else
  # --- Path 2: Fallback (Bug #15840) — cache file + additionalContext ---
  SAFE_VARS="OBSIDIAN_VAULT OBSIDIAN_HOST OBSIDIAN_PORT N8N_BASE_URL"
  CONTEXT_LINES=""
  while IFS= read -r line || [ -n "$line" ]; do
    [ -z "$line" ] && continue
    varname="${line%%=*}"
    if echo "$SAFE_VARS" | grep -qw "$varname"; then
      CONTEXT_LINES="${CONTEXT_LINES}${line} | "
    else
      CONTEXT_LINES="${CONTEXT_LINES}${varname}=*** | "
    fi
  done <<< "$ALL_LINES"
  SAFE_CONTEXT=$(printf '%s' "$CONTEXT_LINES" | sed 's/"/\\"/g')
  echo '{"systemMessage":"env-loader: '"$LOADED"' vars cached (Bug #15840: CLAUDE_ENV_FILE unset). Fuer Bash: source ~/.config/secrets/.env-cache","hookSpecificOutput":{"additionalContext":"Secrets geladen ('"$LOADED"' vars). Bash-Zugriff: source ~/.config/secrets/.env-cache | '"$SAFE_CONTEXT"'"}}'
fi
exit 0
